import { create } from 'zustand';

export interface StudySpace {
  id: string;
  name: string;
  category: 'Libraries' | 'Reading Rooms' | 'Study Halls' | 'Focus Pods' | 'Group Rooms';
  price: number;
  rating: number;
  reviewsCount: number;
  distance: string;
  availableSeats: number;
  totalSeats: number;
  imageUrl: string;
  description: string;
  amenities: string[];
  location: string;
}

interface SpaceState {
  spaces: StudySpace[];
  setSpaces: (spaces: StudySpace[]) => void;
  favoritedIds: string[];
  toggleFavorite: (spaceId: string) => void;
}

const SEED_SPACES: StudySpace[] = [
  {
    id: '1',
    name: "The Scholar's Haven",
    category: 'Libraries',
    price: 8,
    rating: 4.9,
    reviewsCount: 124,
    distance: '0.8 mi',
    availableSeats: 12,
    totalSeats: 40,
    imageUrl: 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?q=80&w=600&auto=format&fit=crop',
    description: 'A quiet, traditional wood-crafted library space featuring individual high-walled desks, ergonomic leather seating, and warm study lamps. Ideal for intensive exam preparation and deep writing.',
    amenities: ['High-speed Wi-Fi', 'Power Outlets', 'Silent Zone', 'Air Conditioning', 'Printing Station'],
    location: '412 Library Lane, University District',
  },
  {
    id: '2',
    name: 'Vibe Modern Study Hall',
    category: 'Study Halls',
    price: 12,
    rating: 4.7,
    reviewsCount: 89,
    distance: '1.4 mi',
    availableSeats: 24,
    totalSeats: 60,
    imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=600&auto=format&fit=crop',
    description: 'A spacious, natural-light-filled study hall. Features modern modular desks, wireless charging pads, whiteboard areas, and access to a premium coffee counter for quick study breaks.',
    amenities: ['High-speed Wi-Fi', 'Power Outlets', 'Whiteboards', 'Air Conditioning', 'Coffee Station', 'Cafe Access'],
    location: '78 Broad Street, Suite 300',
  },
  {
    id: '3',
    name: 'Apex Soundproof Pods',
    category: 'Focus Pods',
    price: 18,
    rating: 4.9,
    reviewsCount: 42,
    distance: '2.1 mi',
    availableSeats: 3,
    totalSeats: 6,
    imageUrl: 'https://images.unsplash.com/photo-1542744094-3a31f103e35f?q=80&w=600&auto=format&fit=crop',
    description: 'A state-of-the-art acoustic focus pod designed for total visual and auditory isolation. Equipped with height-adjustable desks, customized lighting settings, and air filtration systems.',
    amenities: ['High-speed Wi-Fi', 'USB Chargers', 'Soundproof', 'Air Conditioning', 'Ergonomic Desk'],
    location: '102 Tech Hub Boulevard',
  },
  {
    id: '4',
    name: 'The Reading Oasis',
    category: 'Reading Rooms',
    price: 6,
    rating: 4.6,
    reviewsCount: 76,
    distance: '1.1 mi',
    availableSeats: 8,
    totalSeats: 20,
    imageUrl: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?q=80&w=600&auto=format&fit=crop',
    description: 'A relaxed study environment designed for scanning books, reading literature, and low-stress drafting. Standard amenities include lush armchairs, fireplace background sound, and warm lighting.',
    amenities: ['High-speed Wi-Fi', 'Air Conditioning', 'Comfortable Loungers', 'Free Tea & Coffee', 'Bookshelf Access'],
    location: '19 Park View Plaza',
  },
  {
    id: '5',
    name: 'Synergy Group Suite',
    category: 'Group Rooms',
    price: 25,
    rating: 4.8,
    reviewsCount: 64,
    distance: '3.5 mi',
    availableSeats: 2,
    totalSeats: 4,
    imageUrl: 'https://images.unsplash.com/photo-1517502884422-41eaaced0168?q=80&w=600&auto=format&fit=crop',
    description: 'A private group study room perfect for group projects, brainstorming sessions, and presentations. Equipped with a 55" display screen, a large writing whiteboard wall, and HDMI connections.',
    amenities: ['High-speed Wi-Fi', 'Power Outlets', '4K TV Screen', 'Whiteboard Wall', 'Air Conditioning', 'HDMI Cabling'],
    location: 'Hub 55, Innovation Hub Drive',
  },
  {
    id: '6',
    name: 'Metro Focus Lounge',
    category: 'Focus Pods',
    price: 10,
    rating: 4.5,
    reviewsCount: 95,
    distance: '0.5 mi',
    availableSeats: 5,
    totalSeats: 15,
    imageUrl: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=600&auto=format&fit=crop',
    description: 'High-walled focus desks located in the heart of downtown. Offers mesh ergonomic seating, sound-dampening carpets, and quick access to nearby student cafeterias.',
    amenities: ['High-speed Wi-Fi', 'Power Outlets', 'Air Conditioning', 'Sound Dampening', 'Ergonomic Mesh Chair'],
    location: '88 Commerce Street',
  },
  {
    id: '7',
    name: 'Green Garden Library',
    category: 'Libraries',
    price: 9,
    rating: 4.8,
    reviewsCount: 110,
    distance: '1.2 mi',
    availableSeats: 15,
    totalSeats: 30,
    imageUrl: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?q=80&w=600&auto=format&fit=crop',
    description: 'A glass-roofed library space filled with plants, quiet ventilation, and comfortable chairs. Great for studying in a natural-feeling space.',
    amenities: ['High-speed Wi-Fi', 'Silent Zone', 'Comfortable Chairs', 'Air Conditioning'],
    location: '52 Garden Way, Botanical District',
  },
  {
    id: '8',
    name: 'The Study Grind Café',
    category: 'Study Halls',
    price: 5,
    rating: 4.4,
    reviewsCount: 140,
    distance: '0.6 mi',
    availableSeats: 10,
    totalSeats: 25,
    imageUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=600&auto=format&fit=crop',
    description: 'A student-focused study café. Features low ambient chatter, fast power outlets, and student discounts on refreshments.',
    amenities: ['High-speed Wi-Fi', 'Power Outlets', 'Cafe Access', 'Free Tea & Coffee'],
    location: '23 University Ave',
  },
  {
    id: '9',
    name: 'Nexus Executive Study Suite',
    category: 'Group Rooms',
    price: 30,
    rating: 4.9,
    reviewsCount: 18,
    distance: '2.5 mi',
    availableSeats: 1,
    totalSeats: 2,
    imageUrl: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?q=80&w=600&auto=format&fit=crop',
    description: 'A high-end private double focus suite featuring fully adjustable standing desks, premium curved monitors, and acoustic wall panels.',
    amenities: ['High-speed Wi-Fi', 'Power Outlets', 'Whiteboards', 'Curved Monitors', 'Height-Adjustable Desks'],
    location: '404 Executive Center Dr',
  },
  {
    id: '10',
    name: 'Hush Quiet Lounge',
    category: 'Reading Rooms',
    price: 7,
    rating: 4.6,
    reviewsCount: 55,
    distance: '1.8 mi',
    availableSeats: 14,
    totalSeats: 22,
    imageUrl: 'https://images.unsplash.com/photo-1568667256549-094345857637?q=80&w=600&auto=format&fit=crop',
    description: 'An ultra-quiet reading room with low lighting, comfortable armchairs, and floor heating. Perfect for reading academic articles and books.',
    amenities: ['High-speed Wi-Fi', 'Silent Zone', 'Comfortable Loungers', 'Floor Heating'],
    location: '15 Maple Blvd',
  },
  {
    id: '11',
    name: 'Heritage Arch Library',
    category: 'Libraries',
    price: 11,
    rating: 4.9,
    reviewsCount: 160,
    distance: '1.5 mi',
    availableSeats: 18,
    totalSeats: 50,
    imageUrl: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?q=80&w=600&auto=format&fit=crop',
    description: 'Historic gothic library with tall stained glass, personal oak cubbies, and silent study zones.',
    amenities: ['High-speed Wi-Fi', 'Silent Zone', 'Oak Cubbies', 'Power Outlets'],
    location: '900 Old Main Rd',
  },
  {
    id: '12',
    name: 'Apex Soundproof Pod B',
    category: 'Focus Pods',
    price: 20,
    rating: 4.8,
    reviewsCount: 30,
    distance: '2.1 mi',
    availableSeats: 2,
    totalSeats: 6,
    imageUrl: 'https://images.unsplash.com/photo-1542744095-291753704674?q=80&w=600&auto=format&fit=crop',
    description: 'Sound-isolated acoustic chamber with premium ergonomic seating, height-adjustable desk, and screen casting.',
    amenities: ['Soundproof', 'High-speed Wi-Fi', 'Screen Cast', 'Adjustable Desk'],
    location: '102 Tech Hub Boulevard',
  },
  {
    id: '13',
    name: 'Co-Work Commons',
    category: 'Group Rooms',
    price: 22,
    rating: 4.6,
    reviewsCount: 78,
    distance: '3.1 mi',
    availableSeats: 3,
    totalSeats: 5,
    imageUrl: 'https://images.unsplash.com/photo-1531538606174-0f90ff5dce83?q=80&w=600&auto=format&fit=crop',
    description: 'Group meeting space with dry-erase walls, rolling whiteboards, and full media presentation setup.',
    amenities: ['Whiteboards', '4K TV Screen', 'High-speed Wi-Fi', 'Conference Table'],
    location: '240 Innovation Way',
  },
  {
    id: '14',
    name: 'Cosy Nook Bookroom',
    category: 'Reading Rooms',
    price: 5,
    rating: 4.5,
    reviewsCount: 88,
    distance: '0.9 mi',
    availableSeats: 9,
    totalSeats: 15,
    imageUrl: 'https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?q=80&w=600&auto=format&fit=crop',
    description: 'Charming wood-paneled reading room with fireplace, plush armchairs, and complimentary tea bar.',
    amenities: ['Complimentary Tea', 'Armchairs', 'Quiet Zone', 'High-speed Wi-Fi'],
    location: '302 Pine St',
  },
  {
    id: '15',
    name: 'Skyline Study Lab',
    category: 'Study Halls',
    price: 14,
    rating: 4.7,
    reviewsCount: 92,
    distance: '1.9 mi',
    availableSeats: 32,
    totalSeats: 80,
    imageUrl: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?q=80&w=600&auto=format&fit=crop',
    description: 'Penthouse study hall with panoramic windows, collaborative zones, and wireless charging stations.',
    amenities: ['Panoramic Views', 'Wireless Chargers', 'Study Desks', 'High-speed Wi-Fi'],
    location: '800 Grand Ave, Floor 12',
  },
  {
    id: '16',
    name: 'Silicon Pods',
    category: 'Focus Pods',
    price: 16,
    rating: 4.7,
    reviewsCount: 52,
    distance: '2.8 mi',
    availableSeats: 4,
    totalSeats: 10,
    imageUrl: 'https://images.unsplash.com/photo-1556761175-b813f53a362d?q=80&w=600&auto=format&fit=crop',
    description: 'Tech-equipped study pod with USB-C interfaces, visual privacy blinders, and task lights.',
    amenities: ['Visual Privacy', 'USB-C Charging', 'Task Lighting', 'High-speed Wi-Fi'],
    location: '120 Sand Hill Rd',
  },
  {
    id: '17',
    name: 'North Campus Library',
    category: 'Libraries',
    price: 10,
    rating: 4.8,
    reviewsCount: 205,
    distance: '1.0 mi',
    availableSeats: 25,
    totalSeats: 100,
    imageUrl: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?q=80&w=600&auto=format&fit=crop',
    description: 'Modern university library featuring three floors of desks, computer terminals, and audio labs.',
    amenities: ['Audio Lab', 'Computer Terminals', 'High-speed Wi-Fi', 'Printers'],
    location: '200 University Crescent',
  },
  {
    id: '18',
    name: 'Collaborative Hub',
    category: 'Group Rooms',
    price: 24,
    rating: 4.5,
    reviewsCount: 39,
    distance: '3.0 mi',
    availableSeats: 2,
    totalSeats: 5,
    imageUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=600&auto=format&fit=crop',
    description: 'Spacious group room containing wireless presentation screens, rolling chairs, and acoustic ceiling tiles.',
    amenities: ['Presentation Screens', 'Rolling Chairs', 'High-speed Wi-Fi', 'Air Conditioning'],
    location: '45 Tech Plaza',
  },
  {
    id: '19',
    name: 'Velvet Lounge Reading Room',
    category: 'Reading Rooms',
    price: 8,
    rating: 4.6,
    reviewsCount: 71,
    distance: '1.3 mi',
    availableSeats: 11,
    totalSeats: 20,
    imageUrl: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?q=80&w=600&auto=format&fit=crop',
    description: 'Luxury lounge with leather armchairs, ambient light control, and selection of national journals.',
    amenities: ['Leather Seating', 'Ambient Light Control', 'High-speed Wi-Fi', 'Quiet Zone'],
    location: '180 Park Ave',
  },
  {
    id: '20',
    name: 'Foundry Study Hall',
    category: 'Study Halls',
    price: 9,
    rating: 4.4,
    reviewsCount: 119,
    distance: '1.7 mi',
    availableSeats: 20,
    totalSeats: 50,
    imageUrl: 'https://images.unsplash.com/photo-1497215842964-222b430db214?q=80&w=600&auto=format&fit=crop',
    description: 'Industrial-loft converted study hall with warm brick aesthetics, concrete study benches, and high ceilings.',
    amenities: ['Warm Brick Aesthetic', 'Concrete Benches', 'High-speed Wi-Fi', 'Power Outlets'],
    location: '55 Foundry Rd',
  },
  {
    id: '21',
    name: 'Atrium Glass Library',
    category: 'Libraries',
    price: 12,
    rating: 4.9,
    reviewsCount: 144,
    distance: '1.1 mi',
    availableSeats: 14,
    totalSeats: 45,
    imageUrl: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?q=80&w=600&auto=format&fit=crop',
    description: 'A light-filled atrium library, with towering glass walls, quiet seating, and personal study pods.',
    amenities: ['Atrium Views', 'Personal Pods', 'High-speed Wi-Fi', 'Silent Zone'],
    location: '72 Glass Dome Ave',
  },
  {
    id: '22',
    name: 'Capsule Pod Zone',
    category: 'Focus Pods',
    price: 15,
    rating: 4.6,
    reviewsCount: 61,
    distance: '2.0 mi',
    availableSeats: 6,
    totalSeats: 12,
    imageUrl: 'https://images.unsplash.com/photo-1542744095-291753704674?q=80&w=600&auto=format&fit=crop',
    description: 'Futuristic capsule focus pods with adjustable air ventilation, white noise generator, and multi-color task lights.',
    amenities: ['White Noise', 'Ventilation Controls', 'Color Task Lights', 'High-speed Wi-Fi'],
    location: '18 Capsule Plaza',
  },
  {
    id: '23',
    name: 'Summit Group Hall',
    category: 'Group Rooms',
    price: 28,
    rating: 4.8,
    reviewsCount: 29,
    distance: '3.3 mi',
    availableSeats: 2,
    totalSeats: 4,
    imageUrl: 'https://images.unsplash.com/photo-1517502884422-41eaaced0168?q=80&w=600&auto=format&fit=crop',
    description: 'Boardroom-style group room with premium microphones, high-definition webcam, and interactive screen.',
    amenities: ['Boardroom Layout', 'HD Webcam', 'Microphone Setup', 'Interactive Screen'],
    location: '900 Summit Ridge Dr',
  },
  {
    id: '24',
    name: 'Sanctuary Reading Room',
    category: 'Reading Rooms',
    price: 8,
    rating: 4.7,
    reviewsCount: 68,
    distance: '1.6 mi',
    availableSeats: 7,
    totalSeats: 18,
    imageUrl: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?q=80&w=600&auto=format&fit=crop',
    description: 'Peaceful reading sanctuary with comfortable couches, high-quality noise cancellation headsets, and soft ambient sounds.',
    amenities: ['Couches', 'Noise-Canceling Headsets', 'Ambient Sounds', 'High-speed Wi-Fi'],
    location: '12 Sanctuary Lane',
  },
  {
    id: '25',
    name: 'Centennial Study Center',
    category: 'Study Halls',
    price: 11,
    rating: 4.7,
    reviewsCount: 154,
    distance: '1.3 mi',
    availableSeats: 22,
    totalSeats: 60,
    imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=600&auto=format&fit=crop',
    description: 'Massive study center featuring modular tables, printing bar, and full vending dining area for quick snacks.',
    amenities: ['Modular Tables', 'Printing Bar', 'Vending Machines', 'High-speed Wi-Fi'],
    location: '1 Centennial Way',
  },
];

export const useSpaceStore = create<SpaceState>((set) => ({
  spaces: SEED_SPACES,
  setSpaces: (spaces) => set({ spaces }),
  favoritedIds: [],
  toggleFavorite: (spaceId) => set((state) => ({
    favoritedIds: state.favoritedIds.includes(spaceId)
      ? state.favoritedIds.filter((id) => id !== spaceId)
      : [...state.favoritedIds, spaceId]
  })),
}));
